apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consumer01
generatorOptions:
  disableNameSuffixHash: true

# ConfigMaps para archivos Astro
configMapGenerator:
  - name: consumer-catalogue-ui-astro
    files:
      - index.astro.mjs=astro/catalogue-ui/index.astro.mjs
      - SearchTabs.js=astro/catalogue-ui/SearchTabs.js

