apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authority01
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: onboarding-i18n
    files:
      - en.json=json/simpl-fe-onboarding/onboarding/en.json
  - name: onboarding-i18n-ecl
    files:
      - en.json=json/simpl-fe-onboarding/onboarding/en.json
  - name: onboarding-i18n-eui
    files:
      - en.json=json/simpl-fe-onboarding/onboarding/en.json

# No incluyas patches de Deployment
resources: []
