apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authority01
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authority-onboarding-html
    files:
      - index.html=html/simpl-fe-onboarding/onboarding/index.html
      